server:
  port: 8443

service:
  discovery:
    userManagementServiceUri: http://localhost:8680
    eventsServiceUri: http://localhost:8780
    fallbackUri: http://localhost:8880

management:
  endpoints:
    web:
      base-path: /api-gateway
  endpoint:
    health:
      enabled: true
    info:
      enabled: true

info:
  app:
    version: @project.version@
    serviceName: @project.name@-${info.app.env}

circuit:
  breaker:
    timeoutDurationInSeconds: 1